### ISSUE TITLE
Code coverage .gcda:stamp mismatch with notes file

### ISSUE THREAD

**Issue by cbgeo** [kks32/lbm-dem#1]
Running `lcov --list coverage.info --rc lcov_branch_coverage=1` shows `*.gcda:stamp mismatch with notes file`.

**Comment by kks32** [comment]
If a file is compiled twice. It will cause that gcno file will be updated by new timestamp that will not match to gcda file anymore. Re-executing `lbmdemtest` in `after_success` part for Code Coverage matrix is likely to fix the issue.
